services:
  yumiwiki:
    build:
      context: yumiwiki
      dockerfile: yumiwiki/Dockerfile
    container_name: yumiwiki-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env